### ISSUE TITLE
Question: Define route by siteaccess

### ISSUE THREAD

**Issue by ahmed-bhs** [netgen/NetgenSiteAccessRoutesBundle#6]
I'm wondering if is it possible to define tow routes having same path, in wish way the first route works on the first siteaccess and the second one works on the second.

*For Example:*

Imagine we have 2 siteaccess: site_1 and site_2

Under routing.yml we have this 2 routing configurations:

```
site_1_bundle.sitemap:
    path:       /sitemap.xml
    controller: Site1Bundle\Controller\SitemapController::index
```

```
site_2_bundle.sitemap:
    path:       /sitemap.xml
    controller: Site2Bundle\Controller\SitemapController::index
```

**Comment by emodric** [comment]
Hi!

Unfortunatelly, it is not possible. This is a limitation of eZ kernel and the way siteaccesses are implemented, in combination with how Symfony parses the routing configuration.

By default, you can either have a route available on all siteaccesses, or make the route not aware of siteaccess at all (e.g. Instead of `/eng/foo` and `/ger/foo`, you would only have `/foo`).

In your example, Symfony would just match the first route and use the `Site1Bundle\Controller\SitemapController::index` controller for `/sitemap.xml`, no matter what siteaccess are you on.

This is not something any user code can change, you'd actually need to implement the logic yourself.

Something like this comes to mind, using a special controller that forwards the request to manually specified controllers in `defaults` section:

```
my_route:
    path: /foo
    controller: AppBundle\Controller\SiteAccessAwareController::forward
    defaults:
        siteaccess_controllers:
            eng: AppBundle\Controller\EnglishController::index
            ger: AppBundle\Controller\GermanController::index
```

However, this can be tricky to implement, seeing how different controllers for different siteaccesses could have different signatures for action methods.
